### ISSUE TITLE
Zoom connector client (8.11 Preview) 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1420]
## New Zoom connector
New connector client to be released with 8.11 in Preview.
Preliminary date for 8.11 Feature Freeze: Tue, Oct 03 2023

### Acceptance criteria
- [x] Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) 
- [x] reuse old TDD
- [x] update QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
     - [x] #1503
     - [x] #1542
     - [x] #1571
- [x] Functional tests performed
- [x] #1563
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
   - [x] if no new libs are needed, skip compatibility tests

**Comment by abhishekjoshi-crest** [comment]
Updates - [24th August - 30th August]:

- Both PR's got merged to connector branch
    - Implementation(#1504) 
    - Functional test(#1543)
- After completion of internal testing will raise final PR to main
- Meanwhile working on documentation

**Comment by abhishekjoshi-crest** [comment]
Updates - [31st August - 6th September]:

- Connector code moved to main #1504 
- Documentation PR merged to main #1564 
- Functional tests are performed

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni I have uploaded the demo of Zoom Connector on [google drive](https://drive.google.com/file/d/163xXnz8i_3W4rtcSvOymSAva0LUGTbaT/view?usp=drive_link).
Please take a look and mark the task in the above list as done.

**Comment by abhishekjoshi-crest** [comment]
Updates - [11th August - 13th September]:

- Enhancement PR #1623 raised for support of recording age
- Addressed suggested nits for the same

**Comment by seanstory** [comment]
Engineer sign-off granted ✅

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni From the above mentioned list, the below points are done from our end.

- Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) - **Done**
- Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf) - **Done**
- Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix
-  if no new libs are needed, skip compatibility tests - **Skipped compatibility test**

 
 Could you please mark them as **Done** and close this issue?

**Comment by abhishekjoshi-crest** [comment]
Updates - [14th August]:

- Enhancement PR #1623 got merged

**Comment by danajuratoni** [comment]
Closing as done! 🎉
