### ISSUE TITLE
Exchange Online(Outlook) connector client (8.11 Preview) 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1421]
## New Exchange Online connector
New connector client to be released with 8.11 in Preview, to offer support for Exchange Online.
Preliminary date for 8.11 Feature Freeze: Tue, Oct 03 2023

### Acceptance criteria
- [x] Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) 
- [x] reuse old TDD
- [x] update QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
    - [x] Ping and Indexing
    - [ ] ~End-to-end tests~
- [x] Functional tests performed
- [x] #1640
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
   - [x] if no new libs are needed, skip compatibility tests

**Comment by moxarth-elastic** [comment]
Updates of past 2 weeks:

- Raised Outlook PR with Ping and Indexing Functionalities - https://github.com/elastic/connectors-python/pull/1501
    - Got few comments and addressing them.

**Comment by moxarth-elastic** [comment]
Updates - [7th - 14th September]

- Merged Ping + Indexing PR - https://github.com/elastic/connectors-python/pull/1629
- Raised a documentation PR - https://github.com/elastic/connectors-python/pull/1641
- Looking into mocking SOAP apis for functional tests

**Comment by moxarth-elastic** [comment]
Updates - [15th September - 21st September]

- Merged documentation PR - https://github.com/elastic/connectors-python/pull/1641
- Ongoing thread for Outlook E2E - https://crestdatasystems.slack.com/archives/C02AV5C8ZDE/p1693201602663079

**Comment by moxarth-elastic** [comment]
@danajuratoni we've uploaded the [demo](https://drive.google.com/file/d/1XQ1K8n-3s7Cu8LmZPwxZk-y28fuqeWsa/view?usp=drive_link) for the Outlook connector with cloud platform, so you can make the task as done. Also, functional tests were also completed so that can also be marked as done.

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan 

- Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
-  if no new libs are needed, skip compatibility tests - Done

Please mark this task as Done

**Comment by danajuratoni** [comment]
@jedrazb can we get the engineer Sign off?

**Comment by jedrazb** [comment]
Engineer sign off granted ✅ 

cc @leemthompo we need to get the outlook [reference docs](https://github.com/elastic/connectors-python/blob/main/docs/reference/outlook.md) ported to [elastic docs](https://www.elastic.co/guide/en/enterprise-search/master/connectors-outlook.html)

**Comment by danajuratoni** [comment]
Closing as complete!
