### ISSUE TITLE
Teams connector client (8.11 Preview) 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1422]
## New Teams connector
New connector client to be released with 8.11 in Preview.
Preliminary date for 8.11 Feature Freeze: Tue, Oct 03 2023

### Acceptance criteria
- [x] Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) 
- [x] reuse old TDD
- [x] update QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
- [x] Functional tests performed
- [x] Connector client documentation merged in repo 
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
   - [ ] if no new libs are needed, skip compatibility tests

**Comment by akanshi-elastic** [comment]
Working on ping, indexing and unit test cases for microsoft teams.

**Comment by akanshi-elastic** [comment]
Raised ping PR on github, working on indexing feature.

**Comment by akanshi-elastic** [comment]
- ping for ms teams merged
-Raised PR for indexing
-working on e2e for teams

**Comment by akanshi-elastic** [comment]
indexing for ms teams merged
-Raised  e2e pr for teams

**Comment by akanshi-elastic** [comment]
E2E PR merged for teams
- Working on teams documentation
- Fixing few bugs while testing the connector internally. Will raise PR in few days

**Comment by khushbu-elastic** [comment]
@danajuratoni  @danajuratoni  Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/file/d/1Jsu07HQDxXgyYodCuqbx_Ynz0AIjuNG-/view?usp=drive_link) is uploaded

**Comment by jedrazb** [comment]
Engineering sign off given ✅

**Comment by jedrazb** [comment]
cc @leemthompo there are bunch of connectors added to 8.11 - we need track moving this to official docs: https://github.com/elastic/connectors-python/tree/main/docs/reference

**Comment by leemthompo** [comment]
@jedrazb I got you 😄: https://github.com/elastic/enterprise-search-team/issues/5920

**Comment by danajuratoni** [comment]
Closing as complete!
