### ISSUE TITLE
Box connector client (8.11 Preview) 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1424]
## New Box connector
New connector client to be released with 8.11 in Beta.
Preliminary date for 8.11 Feature Freeze: Tue, Oct 03 2023

### Acceptance criteria
- [x] Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) 
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
    - [ ] Scoped Advanced Sync Rules, not to be implemented in this version
    - [ ] Scoped DLS, not to be implemented in this version
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
    - [x] #1630
    - [x] #1697
- [x] Functional tests performed
- [ ] ~Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud~ deferred
- [x] Connector client documentation merged in repo 
    - [x] #1727
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix

**Comment by parth-elastic** [comment]
Progress summary [1st Sept - 14th Sept]:

- Updated Connector timeline [We can tick the checkbox as Done]
- Shared TDD and Test Cases in GDrive [We can tick the checkbox as Done]
- Shared QA Plan & Test cases in GDrive [We can tick the checkbox as Done]
- Started working on Ping & Indexing
- Raised a PR for Ping & Indexing #1630

**Comment by parth-elastic** [comment]
Progress summary [15th Sept - 21st Sept]:

- Awaiting Tim's Review on the PR #1630 
- Started working on e2e
- Raised a Draft PR, Will open once Indexing get's merged

**Comment by danajuratoni** [comment]
@parth-elastic which PRs are still needed to finalize work on Box? Any other than https://github.com/elastic/connectors-python/pull/1700?

**Comment by parth-elastic** [comment]
No Functional PR other than #1700 is remaining.
Once that PR merges, we will be raising a documentation PR for the box connector.

We've also verified functional tests and everything is working fine.

**Comment by parth-elastic** [comment]
Progress summary [21 Sept - 5 Oct]:

Box Indexing [PR](#1631) and E2E [PR](#1661 ) was merged
Raised Box Documentation [PR](#1728) and resolving comments

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix is completed. Please mark it as Done in the above checklist.
