### ISSUE TITLE
Add connectors-python to PyPI

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors-python#1490]
### Problem Description
PyPI (Python Package Index) is where most things get `pip install`'d from. If we want folks to be able to `pip install connectors-python`, we need to get ourselves added to PyPI.

### Proposed Solution
- [ ] discover what it would take to get added to PyPI
- [ ] put together a plan of what we would publish to PyPI
  - would it include the `elastic-ingest` executable?
  - would it include our makefile and dockerfile?
  - would it be extensible, or useful mainly if you want OOTB connectors?
- [ ] Either get us added, document a plan for next steps, or capture why we couldn't/shouldn't.

**Comment by artem-shelkovnikov** [comment]
Let's drop this task?

**Comment by seanstory** [comment]
I don't see us doing this in the short term. But I think it's worth leaving as an open issue, since it at least sends a signal to the community that:

1. we're aware that were not in PyPi
2. that we'd like to be

I think it's still a while down the road, but I'd like to clean up the code enough that it could be imported as a library and used elsewhere - like in notebooks.
