### ISSUE TITLE
Sync personal drives in Google Drive connector

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors-python#1508]
### Problem Description
Right now, the Google Drive connector can sync shared drives and the documents that have been shared with it (individually or through groups). It cannot currently sync documents that are unshared with it, but merely in the same google drive organization/tenant/domain. 

### Proposed Solution
https://developers.google.com/cloud-search/docs/guides/delegation says:
> A service account with delegated authority can impersonate any user, including users with access to Cloud Search.

This should let us iterate through users, impersonate them, and then list their private drive documents.

- [ ] discover if this is possible (brief poc/demo)

- if possible:
  - [ ] make this behavior configurable
  - [ ] ensure this doesn't lead to duplicate documents being synced (through sharing AND through presence in a private drive)
  - [ ] document any necessary setup steps to get the Service Account to be capable of this

### Alternatives
- "private content sources" a-la workplace search, where one connector is set up per individual user. This leads to lots of redundant data, extra opt-in manual overhead, and slower getting-started experience for the end user.
- sync shared drives and shared documents only. This works for the google drive customers we've had thus far, but new customers are flagging that this may be insufficient.
- sync shared drives and "target audience" files only. This might help for some customers, but wouldn't help for the use case where an individual wants to search over just their private notes.

**Comment by jedrazb** [comment]
We might consider following approach:
- First use admin directory API to list all users in org.
- Impersonate each user and fetch their my drives docs.
- Somehow handle duplicate docs in the discovery phase (e.g. same doc in multiple my drives via a target audience)
- Then we impersonate admin to fetch all content form shared drives.

Benefits:
- No need to sharing anything manually with service account in this approach.

**Comment by DianaJourdan** [comment]
@jedrazb is the PR you linked going to close this issue? Should we plan more effort in the next sprint?

**Comment by jedrazb** [comment]
> is the PR you linked going to close this issue? Should we plan more effort in the next sprint?
@DianaJourdan the PR should fix this issue completely. I would need some time to make the POC production-ready in the next sprint
