### ISSUE TITLE
Confluence Cloud & Server connector client (8.8 Beta)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#541]
## New Confluence connector
New connector client to be released with 8.8 in Beta.
Preliminary date for **8.8 Feature Freeze**:  Tue, Apr 25 2023

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
     - https://github.com/elastic/connectors-python/tree/confluence-connector
- [x] Functional tests performed
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud 
     - Report uploaded on [GDrive](https://docs.google.com/document/d/1mWqjbd0a-2hlUbMLTn1exzB_9Wu0GFg9CUY6bsgNxYA/edit?usp=share_link)
- [x] Connector client documentation in repo 
     - https://github.com/elastic/connectors-python/pull/647
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x]  Ingestion engineer added a comment to this ticket to sign off
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
    - [x] https://github.com/elastic/connectors-python/issues/861

**Comment by vidok** [comment]
signing off on behalf of the ingestion engineer.

**Comment by sphilipse** [comment]
Kibana PR: https://github.com/elastic/kibana/pull/157167

**Comment by danajuratoni** [comment]
Marking epic as complete.
