### ISSUE TITLE
Dropbox connector client (8.9/8.10 Beta)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#872]
## New Dropbox connector
New connector client to be released with 8.9 in Beta.
Preliminary date for 8.9 Feature Freeze: Tue, Jun 20 2023

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] TDD reviewed by engineer and PM
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan reviewed by engineer and PM
- [x] Code merged in main following the defined PR process
     - [x] #917
     - [x] #1004
     - [x] #1175
     - [x] #1176
     - [x] #1232
- [x] https://github.com/elastic/connectors-python/issues/949
- [x] Functional tests performed
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud 
- [x] 8.9 Connector client documentation merged in repo 
    - [x] #1103
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
- [x] Compatibility tests for running connector as native in Cloud
- [x] 8.10 documentation updates / release notes

**Comment by danajuratoni** [comment]
@prashant-elastic could you assign an engineer to this epic as discussed last time? Thanks!

**Comment by danajuratoni** [comment]
@vidok added "reviewed by engineer and PM" as AC in this epic. Please drop a comment when you've reviewed the documents so I can mark them done. Thanks!

**Comment by moxarth-elastic** [comment]
**Updates - [4th May - 10th May]**

- Shared TDD with the elastic team
    - Pending Review
- Started working on Ping Functionality
- Started writing test cases

**Comment by moxarth-elastic** [comment]
Updates - [18th May - 24th May]
- [Ping PR](https://github.com/elastic/connectors-python/pull/918) is under review
    - Addressed Dmitry's suggestions and re-requested his review.
- Implementation of indexing feature is in progress

**Comment by moxarth-elastic** [comment]
**Updates - [25th May - 31st May]**

- [Ping PR](https://github.com/elastic/connectors-python/pull/918) got merged.
- Implementation for indexing is completed and testing is in progress.
    - PR will be raised soon
- Start working on E2E

**Comment by moxarth-elastic** [comment]
Updates - [1st June - 8th June]

- Raised a Dropbox [indexing PR](https://github.com/elastic/connectors-python/pull/1005)
    - Addressing PR comments of Dmitrii
- Started working on E2E and playing with some dropbox docker images.
- Since the Dropbox connector with SDK is performing slow, we tried a POC with low level APIs using `aiohttp`.
    - The performance seems good with `aiohttp` compared to `dropbox sdk`

**Comment by danajuratoni** [comment]
@moxarth-elastic could we make sure the connector is tested with [Dropbox Paper](https://www.dropbox.com/paper/start) as well?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic could we make sure the connector is tested with [Dropbox Paper](https://www.dropbox.com/paper/start) as well?

@danajuratoni we've already tested the connector with Dropbox Paper. Syncing was working as expected for paper document, but there is a [limitation](https://docs.google.com/document/d/1-OiD5Q86vF1JvUnMtkvvXJTzftkUy9E1Q7fsUJCdYJQ/edit?pli=1#heading=h.ve8fddm0wq55) for delay in updating the paper doc in Dropbox.

One more thing, if we archive the paper docs from Dropbox Paper, it is not getting reflected in Dropbox and so in the connector. So, archived documents won't be indexed.

**Comment by moxarth-elastic** [comment]
Updates - [9st June - 14th June]

- Indexing PR got merged - #1005 
- Working on E2E implementation
    - Tried docker images for E2E, but includes user intervention and some are not supporting Mac(arm64) architecture.
    - Moved to Flask, but facing some SSL related issue for the connector (got in touch with @vidok for the same).

**Comment by moxarth-elastic** [comment]
Updates - [15th June - 21st June]

- E2E updates:
    - SSL error got fixed using `nginx` for some API endpoints but due to partial fix, concluded to stop investing time on E2E and have a simpler version of Dropbox connector.
- Raised a documentation PR - #1104 

Moving to AioHTTP:
- Started updating TDD with the new approach
    - planning to add a new section for AioHTTP

**Comment by moxarth-elastic** [comment]
Updates - [22nd June - 28th June]

- 📄 Documentation PR is in review - #1104 
- 📄 Dropbox TDD is now up-to-date with AioHTTP - [link](https://docs.google.com/document/d/1fVwSCwQnB1XW3_2LWHjRAtDjFUUS2bl-MfThpITqxyI)
- Kicked of the connector implementation with AioHTTP

**Comment by moxarth-elastic** [comment]
Updates - [29th June - 5th July]

- 📄 Address PR comments and requested a review for documentation PR - #1104 
- Raised a functional PR for dropbox with aiohttp - #1177

**Comment by parth-elastic** [comment]
Updates - [29th June - 5th July]


- Started working on Advanced sync rules for Dropbox

**Comment by danajuratoni** [comment]
>Syncing was working as expected for paper document, but there is a [limitation](https://docs.google.com/document/d/1-OiD5Q86vF1JvUnMtkvvXJTzftkUy9E1Q7fsUJCdYJQ/edit?pli=1#heading=h.ve8fddm0wq55) for delay in updating the paper doc in Dropbox.
One more thing, if we archive the paper docs from Dropbox Paper, it is not getting reflected in Dropbox and so in the connector.

@vidok could you please make sure these limitations are documented in the official docs? Thanks!

**Comment by moxarth-elastic** [comment]
Updates - [6th July - 12th July]

- ✅ Documentation PR got merged - https://github.com/elastic/connectors-python/pull/1104
- ✅ E2E PR got merged - https://github.com/elastic/connectors-python/pull/1233
- Addressing comments for Dropbox indexing PR - https://github.com/elastic/connectors-python/pull/1177
    - Internal testing is under progress

**Comment by parth-elastic** [comment]
Updates - [6th July - 12th July]

- About to complete Advanced sync rules implementation for Dropbox, Will raise PR soon after testing

**Comment by parth-elastic** [comment]
Updates - [13th July - 20th July]

- Found one issue related to paper file during internal testing.
- Will raise PR once we fix and test the issue.

**Comment by moxarth-elastic** [comment]
Updates - [13th July - 20th July]

- ✅ Dropbox indexing PR got merged - https://github.com/elastic/connectors-python/pull/1177

**Comment by moxarth-elastic** [comment]
Updates - [20th July - 26th July]

- ✅ Merged Dropbox final PR with `AioHTTP` in `main` branch - https://github.com/elastic/connectors-python/pull/1336
- ✅ Dropbox advanced sync rules documentation PR got merged in main - https://github.com/elastic/connectors-python/pull/1322

**Comment by danajuratoni** [comment]
From @moxarth-elastic 
> Functional and performance testing for the Dropbox connector has been completed.
Marking ACs as done.

**Comment by DianaJourdan** [comment]
@wangch079 could you please check the AC _Sign off given from an engineer in Ingestion_ as Dmitrii is on PTO?
-  Code backported to the correct version
-  Automated tests to 90% coverage

**Comment by wangch079** [comment]
Hi @DianaJourdan , confirm that the automated tests is above 90% coverage, but the PR #1336 is not backported to 8.9

**Comment by moxarth-elastic** [comment]
> Hi @DianaJourdan , confirm that the automated tests are above 90% coverage, but PR #1336 is not backported to 8.9

Yes @wangch079 , PR #1336 will be a part of 8.10 so it's going to backport to 8.9.
cc: @danajuratoni

**Comment by danajuratoni** [comment]
PR https://github.com/elastic/connectors-python/pull/1336 will be a part of 8.10 so it's **not** going to be backported to 8.9.

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan We have verified the below mentioned points:

- Demo of the connector in latest builds in Elastic Cloud in [[GDrive](https://drive.google.com/file/d/1FrUr6ORrCDJrGHa2-mTjYYUXV8a8eX-A/view?usp=sharing)]
- Regression test suite performed for the release along with QA day for all supported OS in Mac OS, Alma Linux 8, Rocky Linux 8, Cent OS7
- Compatibility tests for running connector as native in Cloud

Could you please check them and mark the above mentioned points as done, for this task?

**Comment by danajuratoni** [comment]
Has the documentation been updated with the latest changes and the known limitations mentioned above? 
Are there any release notes needed? cc: @leemthompo

**Comment by moxarth-elastic** [comment]
> We have noted the Paper limitation [here](https://www.elastic.co/guide/en/enterprise-search/current/connectors-dropbox.html#connectors-dropbox-documents-and-syncs). Have other issues cropped up that we need to flag?

No, nothing else. The documentation is up-to-date.

**Comment by moxarth-elastic** [comment]
@leemthompo There will be few changes happen regarding advanced sync rules and end-to-end testing in 8.10 documentation. The advanced sync rule is already updated in `main`. But, need to update the e2e as per the following:

------------------------------------------------------------------------------------------------------------------------
The connector framework enables operators to run functional tests against a real data source. Refer to [Connector testing](https://www.elastic.co/guide/en/enterprise-search/master/build-connector.html#build-connector-testing) for more details.

To perform E2E testing for Dropbox connector, run the following command:

```shell
$ make ftest NAME=dropbox
```

ℹ️ Users can generate the performance report using an argument i.e. `PERF8=yes`. Users can also mention the size of the data to be tested for E2E test amongst SMALL, MEDIUM and LARGE by setting up an argument `DATA_SIZE=SMALL`. By Default, it is set to `MEDIUM`.

ℹ️ Users do not need to have a running Elasticsearch instance or a Dropbox source to run this test. The docker compose file manages the complete setup of the development environment, i.e. both the mock Elastic instance and mock Dropbox source using the Flask module.

------------------------------------------------------------------------------------------------------------------------

**Comment by danajuratoni** [comment]
Keep up the good work, marking this as done!
