### ISSUE TITLE
OneDrive connector client (8.10/8.11 Beta)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#873]
## New OneDrive connector
New connector client to be released with 8.10 in Beta.
Preliminary date for 8.10 Feature Freeze: Tue, Aug 15 2023

### Acceptance criteria
- [x] Updated [connector timeline](https://docs.google.com/spreadsheets/d/1ZRK-ospXAbE624m8g9UGKUGXbyWECAjW4401b0-ymQw/edit#gid=1132430678) 
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] #1432
     - [x] #1293
     - [x] #1413
     - [x] #1415
- [x] #1524
- [x] Functional tests performed
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud 
- [x] Connector client documentation merged in repo 
     - [x] #1438
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
- [x] Compatibility tests for running connector as native in Cloud

**Comment by praveen-elastic** [comment]
Updates for [2nd June to 8th June]:
- Started exploring OneDrive Data Source
- Referred Microsoft Graph APIs for OneDrive 
- API Analysis on MS Graph Explorer
- Kicked off a Technical Design Document for OneDrive connector

**Comment by praveen-elastic** [comment]
Updates for this week:

- Shared the Design Documentation and Test Plan with the Team.
- Address comments in the TDD.
- Took a call with Chenhui to discuss few points regarding OneDrive Connector.

**Comment by praveen-elastic** [comment]
- Added Sync rules schema in the TDD
- POC on validation and connection to OneDrive 
- Kicked off the implementation of ping and configuration fields

**Comment by praveen-elastic** [comment]
Updates for [13th July to 20th July]

- Raised a PR for Implementation of Ping and Configuration
- Addressed Comments on the PR

**Comment by praveen-elastic** [comment]
Updates for [21st July to 27th July]

- PR for OneDrive ping got merged
- Started working on Indexing Implementation

**Comment by praveen-elastic** [comment]
Updates for this week:

- Completed Indexing implementation
- Started with Sync Rules schema definition and implementation.

**Comment by praveen-elastic** [comment]
Updates for the week [3rd August to 10th August]

- Raised a PR for indexing implementation
- On-going discussion related to API to be used for sync-rules.
-  Worked on E2E (FTest) feature, completed it and also raised a PR for it.

**Comment by praveen-elastic** [comment]
Updates for past 2 weeks:

- Addressed comments on OneDrive Indexing and E2E PRs and got those merged to onedrive-connector
- Raised and merged the OneDrive code to main
- Shared a draft PR highlighting implementation for Sync Rules
- Addressed the suggestions and Sync Rules PR is now ready to review

**Comment by danajuratoni** [comment]
@praveen-elastic is there a doc draft? we'll need the documentation to be finished next week, so that the docs team can finalize their work before the connector goes live. cc: @leemthompo

**Comment by praveen-elastic** [comment]
Oops, sorry, looks like i missed mentioning that in the updates. It is already merged to the main branch https://github.com/elastic/connectors-python/pull/1439

**Comment by praveen-elastic** [comment]
@danajuratoni Link to Documentation of OneDrive Connector https://github.com/elastic/connectors-python/blob/main/docs/reference/onedrive.md

**Comment by danajuratoni** [comment]
Thanks @praveen-elastic! @leemthompo seems we're good to go. cc: @ppf2 new OneDrive connector doc is available

**Comment by praveen-elastic** [comment]
Updates - [24th August - 30th August]

- Addressed the comments in the Sync Rules PR and the PR was merged to `main` today
- Checked the Performance Report for the connector

**Comment by danajuratoni** [comment]
@wangch079 Is the sign off given from an engineer done?

**Comment by danajuratoni** [comment]
@praveen-elastic are the regression and compatibility tests for OneDrive (without advanced sync rules) done? cc: @DianaJourdan

**Comment by wangch079** [comment]
>@wangch079 Is the sign off given from an engineer done?

Hi @danajuratoni confirmed these two points and signed off:

> - [ ] Code backported to the correct version
> - [ ]  Automated tests to 90% coverage

**Comment by leemthompo** [comment]
Just for clarity, confirming that the [doc page](https://www.elastic.co/guide/en/enterprise-search/8.10/connectors-onedrive.html) went live last week on 8.10 branch 🎉

**Comment by praveen-elastic** [comment]
> @praveen-elastic are the regression and compatibility tests for OneDrive (without advanced sync rules) done? cc: @DianaJourdan

Yes, those are completed.

**Comment by khushbu-elastic** [comment]
@danajuratoni  @DianaJourdan Demo of the connector is uploaded in latest builds in Elastic Cloud in [[GDrive](https://drive.google.com/file/d/1A3RrA9utAzaA3OshqLfpOioUuRjd-GMW/view?usp=drive_link)]. Please check the same and mark the task as done.
